name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up the test environment
        run: make dev-setup
      - name: Run tests
        run: |
          make test PYTEST_EXTRA_ARGS="--cov=giftless"
          coverage xml
      - uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: cca5a6743728de037cb47d4a845e35c682b4469c0f9c52851f4f3824dd471f87
